"""Contracts for scheduler runtime persistence backends."""

from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

try:
    from models import PlanItemRecord
except ModuleNotFoundError:  # pragma: no cover - package import compatibility
    from backend.models import PlanItemRecord


@runtime_checkable
class SchedulerRuntimeRepository(Protocol):
    def get_persistence_descriptor(self) -> dict: ...
    def get_metadata(self, item: Optional[PlanItemRecord]) -> dict: ...
    def get_required_capabilities(self, item: Optional[PlanItemRecord]) -> list[str]: ...
    def get_child_roles(self, item: Optional[PlanItemRecord]) -> list[str]: ...
    def save_child_roles(self, item: Optional[PlanItemRecord], roles: list[str]) -> list[str]: ...
    def get_child_group(self, item: Optional[PlanItemRecord]) -> Optional[dict]: ...
    def save_child_group(self, item: Optional[PlanItemRecord], group: Optional[dict]) -> Optional[dict]: ...
    def list_children(self, item: Optional[PlanItemRecord]) -> list[dict]: ...
    def find_child_group_entry(
        self,
        item: Optional[PlanItemRecord],
        child_execution_id: str,
    ) -> tuple[Optional[dict], Optional[dict]]: ...
    def get_audit_trail(self, item: Optional[PlanItemRecord]) -> list[dict]: ...
    def append_audit_trail(self, item: Optional[PlanItemRecord], entry: dict, *, limit: int = 50) -> list[dict]: ...
    def get_run_trace(self, item: Optional[PlanItemRecord]) -> list[dict]: ...
    def append_run_trace(self, item: Optional[PlanItemRecord], entry: dict, *, limit: int = 100) -> list[dict]: ...
