"""Reusable agent runtime primitives for vertical agents."""

from .adapters import (
    get_artifact_store,
    get_context_store,
    get_memory_store,
    get_model_provider,
)
from .artifacts import Artifact, ArtifactStore
from .card_schemas import (
    DATETIME_CARD_SCHEMA,
    SEARCH_SUMMARY_CARD_SCHEMA,
    WEATHER_CARD_SCHEMA,
    build_datetime_card_from_text,
    build_search_summary_card,
)
from .child_executor_backends import (
    build_child_executor_sandbox_worker_backend_entry,
    build_child_executor_backend_registry_contract,
    resolve_child_executor_backend,
)
from .child_executor_sandbox_worker_backend import (
    build_child_executor_sandbox_backend_binding_contract,
    build_sandbox_dispatch_attempt_envelope,
    build_sandbox_worker_backend_adapter_contract,
    validate_sandbox_dispatch_attempt,
)
from .context import ContextMessage, ContextStore, ConversationContext
from .events import AgentEvent, AgentEventFactory, AgentEventType
from .execution_loop import (
    ExecutionFallbackResult,
    ExecutionLoopController,
    ExecutionLoopStep,
    ExecutionReflectionResult,
    ExecutionReviewResult,
    ExecutionToolDecision,
    ExecutionToolResult,
)
from .framework_adapters import (
    AgentFrameworkAdapter,
    AgentFrameworkAdapterRegistry,
    FrameworkAdapterHealth,
    LocalFakeFrameworkAdapter,
    NoopFrameworkAdapter,
    get_framework_adapter_registry,
)
from .harness import AgentHarnessFacade, build_agent_harness_facade_contract, create_agent
from .memory import SessionRecord, SessionStore
from .provider_backends import create_default_provider_registry
from .providers import ModelProvider, ModelProviderRegistry, ProviderBackend
from .runtime import AgentRunContext, AgentState
from .runtime_dependencies import (
    EmbeddedRuntimeDependencies,
    EmbeddedRuntimeFactory,
    create_default_embedded_runtime_sdk,
    get_default_embedded_runtime_dependencies,
    get_default_embedded_runtime_factory,
)
from .persistence import build_durable_workspace_production_recovery_gate_contract
from .sdk import (
    EmbeddedAgentRuntimeSDK,
    build_child_executor_context_budget_policy_contract,
    build_child_executor_dispatch_contract,
    build_child_result_merge_handoff_contract,
    build_embedded_sdk_contract,
    validate_embedded_sdk_event_payloads,
)
from .child_executor_dispatcher import (
    build_child_executor_dispatch_attempt_handoff_contract,
    build_child_executor_dispatch_result_handoff_contract,
    build_child_executor_dispatch_result_retry_audit_policy_contract,
)
from .recovery_retry_scheduler import (
    build_recovery_retry_production_scheduler_gate_contract,
    build_recovery_retry_scheduler_contract,
)
from .worker_ownership import (
    PostgresAdvisoryLockExecutionSeam,
    WorkerOwnershipRenewalSupervisor,
    build_worker_ownership_audit_evidence_contract,
    build_worker_ownership_auto_claim_entrypoint_allowlist_contract,
    build_worker_ownership_auto_claim_policy_contract,
    build_worker_ownership_explicit_auto_claim_enablement_gate_contract,
    build_worker_ownership_production_gate_composition_dry_run_contract,
    build_worker_ownership_production_enablement_runtime_config_consumer_contract,
    build_worker_ownership_production_enablement_strategy_contract,
    build_worker_ownership_production_default_enablement_input_source_contract,
    build_worker_ownership_postgres_vendor_lock_target_artifact_binding_contract,
    build_worker_ownership_postgres_vendor_lock_semantics_binding_contract,
    build_worker_ownership_postgres_vendor_lock_production_gate_wiring_decision_contract,
    build_worker_ownership_postgres_rollout_artifact_consumer_contract,
    build_worker_ownership_production_gate_contract,
    build_worker_ownership_rollout_confirmation_decision_contract,
    build_worker_ownership_production_rollout_operationalization_contract,
    build_worker_ownership_renewal_supervisor_contract,
    build_worker_ownership_rollout_readiness_contract,
    build_worker_ownership_postgres_advisory_lock_execution_seam_contract,
    build_worker_ownership_vendor_lock_target_decision_input_contract,
    build_worker_ownership_vendor_lock_target_decision_contract,
    build_worker_ownership_vendor_lock_semantics_contract,
)
from .tool_cache import ToolResultCache, get_tool_result_cache
from .tool_policy import build_policy_engine_tool_policy
from .tools import ArtifactRef, ToolExecutionEnvelope, ToolRenderMode, ToolSpec

__all__ = [
    "Artifact",
    "ArtifactStore",
    "AgentEvent",
    "AgentEventFactory",
    "AgentEventType",
    "AgentFrameworkAdapter",
    "AgentFrameworkAdapterRegistry",
    "AgentHarnessFacade",
    "AgentRunContext",
    "AgentState",
    "EmbeddedRuntimeDependencies",
    "EmbeddedRuntimeFactory",
    "ArtifactRef",
    "DATETIME_CARD_SCHEMA",
    "SEARCH_SUMMARY_CARD_SCHEMA",
    "ContextMessage",
    "ContextStore",
    "ConversationContext",
    "EmbeddedAgentRuntimeSDK",
    "ExecutionLoopController",
    "ExecutionLoopStep",
    "ExecutionFallbackResult",
    "ExecutionReflectionResult",
    "ExecutionReviewResult",
    "ExecutionToolDecision",
    "ExecutionToolResult",
    "FrameworkAdapterHealth",
    "LocalFakeFrameworkAdapter",
    "ModelProvider",
    "ModelProviderRegistry",
    "NoopFrameworkAdapter",
    "PostgresAdvisoryLockExecutionSeam",
    "ProviderBackend",
    "SessionRecord",
    "SessionStore",
    "ToolRenderMode",
    "ToolExecutionEnvelope",
    "ToolResultCache",
    "ToolSpec",
    "WEATHER_CARD_SCHEMA",
    "WorkerOwnershipRenewalSupervisor",
    "build_datetime_card_from_text",
    "build_embedded_sdk_contract",
    "build_agent_harness_facade_contract",
    "build_child_executor_backend_registry_contract",
    "build_child_executor_context_budget_policy_contract",
    "build_child_executor_sandbox_backend_binding_contract",
    "build_child_executor_sandbox_worker_backend_entry",
    "build_sandbox_dispatch_attempt_envelope",
    "build_sandbox_worker_backend_adapter_contract",
    "build_child_executor_dispatch_contract",
    "build_child_executor_dispatch_attempt_handoff_contract",
    "build_child_executor_dispatch_result_handoff_contract",
    "build_child_executor_dispatch_result_retry_audit_policy_contract",
    "build_child_result_merge_handoff_contract",
    "build_durable_workspace_production_recovery_gate_contract",
    "build_search_summary_card",
    "build_policy_engine_tool_policy",
    "build_recovery_retry_production_scheduler_gate_contract",
    "build_recovery_retry_scheduler_contract",
    "build_worker_ownership_audit_evidence_contract",
    "build_worker_ownership_auto_claim_entrypoint_allowlist_contract",
    "build_worker_ownership_auto_claim_policy_contract",
    "build_worker_ownership_explicit_auto_claim_enablement_gate_contract",
    "build_worker_ownership_production_gate_composition_dry_run_contract",
    "build_worker_ownership_production_enablement_runtime_config_consumer_contract",
    "build_worker_ownership_production_enablement_strategy_contract",
    "build_worker_ownership_production_default_enablement_input_source_contract",
    "build_worker_ownership_postgres_vendor_lock_target_artifact_binding_contract",
    "build_worker_ownership_postgres_vendor_lock_semantics_binding_contract",
    "build_worker_ownership_postgres_vendor_lock_production_gate_wiring_decision_contract",
    "build_worker_ownership_postgres_rollout_artifact_consumer_contract",
    "build_worker_ownership_production_gate_contract",
    "build_worker_ownership_rollout_confirmation_decision_contract",
    "build_worker_ownership_production_rollout_operationalization_contract",
    "build_worker_ownership_renewal_supervisor_contract",
    "build_worker_ownership_rollout_readiness_contract",
    "build_worker_ownership_postgres_advisory_lock_execution_seam_contract",
    "build_worker_ownership_vendor_lock_target_decision_input_contract",
    "build_worker_ownership_vendor_lock_target_decision_contract",
    "build_worker_ownership_vendor_lock_semantics_contract",
    "create_agent",
    "create_default_provider_registry",
    "get_artifact_store",
    "get_context_store",
    "get_framework_adapter_registry",
    "get_memory_store",
    "get_model_provider",
    "create_default_embedded_runtime_sdk",
    "get_default_embedded_runtime_dependencies",
    "get_default_embedded_runtime_factory",
    "get_tool_result_cache",
    "validate_embedded_sdk_event_payloads",
    "validate_sandbox_dispatch_attempt",
    "resolve_child_executor_backend",
]
